/*
DDL
CREATE TABLE identificador
(colunnas)
ALTER
DROP
truncate
Replace

--Tablas
--Vistas
--Procedimentos
--Funciones
--Triggers
--TiposDatos y mas
*/
CREATE TABLE PERSONA(
ID INT NOT NULL,
NIF VARCHAR(9) NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO1 VARCHAR(50) NOT NULL,
APELLIDO2 VARCHAR(50) NULL,
CIUDAD VARCHAR(25)NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR (9) NULL,
FECHA_NACIMIENTO DATE NOT NULL,
SEXO CHAR (1) NOT NULL,
TIPO VARCHAR(10) NOT NULL,
CONSTRAINT PK_PERSONA PRIMARY KEY (ID),
CONSTRAINT CKC_SEXO_PERSONA
CHECK (SEXO IN ('M','H','I'))
);

ALTER TABLE PERSONA ADD CONSTRAINT CKC_TIPO_PERSONA
CHECK (TIPO IN('PROFESOR','ALUMNO'));

CREATE TABLE DEPARTAMENTO(
ID INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL
);

--AGREGAR CON ALTER EN ESTE CASO LA LLAVE PRIMARIA
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPARTAMENTO
PRIMARY KEY (ID);

CREATE TABLE GRADO(
ID INT NOT NULL,
NOMBRE VARCHAR(100)NOT NULL,
CONSTRAINT PK_GRADO
PRIMARY KEY (ID)
);

CREATE TABLE CURSO_ESCOLAR
(
ID INT NOT NULL,
ANYO_INICIO INT NOT NULL,
ANYO_FIN INT NOT NULL,
CONSTRAINT PK_CURSO_ESCOLAR
PRIMARY KEY (ID)
);

--A PARTIR DE ESTAS TABAS SE EMPIESAN A METER LLAVES FORANIAS
CREATE TABLE PROFESOR(
ID_PROFESOR INT NOT NULL,
ID_DEPARTAMENTO INT NOT NULL,
CONSTRAINT PK_PROFESOR
PRIMARY KEY (ID_PROFESOR),
--PARTE NUEVA LLAVES FORANEAS
/*PREFIJO NOMENCLATURA FK_TABLAACTUAL_TABLARELACION*/
CONSTRAINT FK_PROFESOR_PERSONA
FOREIGN KEY (ID_PROFESOR) REFERENCES PERSONA(ID),
CONSTRAINT FK_PROFESOR_DEPARTAMENTO
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID)
);

CREATE TABLE ASIGNATURA(
ID INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
CREDITOS FLOAT NOT NULL,
TIPO VARCHAR(10) NOT NULL,
CURSO INT NOT NULL,
CUATRIMESTRE INT NOT NULL,
ID_PROFESOR INT NULL,
ID_GRADO INT NOT NULL,
CONSTRAINT PK_ASIGNATURA
PRIMARY KEY(ID)
);

/*ALTER TABLE ASIGNATURA
ADD CONSTRAINT FK_ASIGNATURA_PROFESOR
FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR
ADD CONSTRAINT FK_ASIGNATURA_GRADO
FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID);*/


ALTER TABLE ASIGNATURA
ADD CONSTRAINT FK_ASIGNATURA_PROFESOR
FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR); 

ALTER TABLE ASIGNATURA
ADD CONSTRAINT FK_ASIGNATURA_GRADO
FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID); 

DROP TABLE ASIGNATURA;-- tenia error en grado y la tuvevque hacerlo d n

CREATE TABLE ALUMNO_X_ASIGNATURA
(
ID_ALUMNO INT NOT NULL,
ID_ASIGNATURA INT NOT NULL,
ID_CURSO_ESCOLAR INT NOT NULL,
CONSTRAINT PK_ALUMNO_X_ASIGNATURA
PRIMARY KEY(ID_ALUMNO, ID_ASIGNATURA, ID_CURSO_ESCOLAR),
CONSTRAINT FK_ALUMNO_X_ASIGNATURA_PERSONA
FOREIGN KEY (ID_ALUMNO) REFERENCES PERSONA(ID),
CONSTRAINT FK_ALUMNO_X_ASIGNATURA_ASIGNATURA
FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA(ID),
CONSTRAINT FK_ALUMNO_X_ASIGNATURA_CURSO_ESCOLAR
FOREIGN KEY (ID_CURSO_ESCOLAR) REFERENCES CURSO_ESCOLAR (ID)
);

DROP TABLE ALUMNO_X_ASIGNATURA CASCADE CONSTRAINTS;
DROP TABLE ASIGNATURA CASCADE CONSTRAINTS;
DROP TABLE PROFESOR CASCADE CONSTRAINTS;
DROP TABLE CURSO_ESCOLAR CASCADE CONSTRAINTS;
DROP TABLE GRADO CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;


CREATE TABLE PERSONA(
    ID               NUMBER(10)   NOT NULL,
    NIF              VARCHAR2(9)  NULL,
    NOMBRE           VARCHAR2(25) NOT NULL,
    APELLIDO1        VARCHAR2(50) NOT NULL,
    APELLIDO2        VARCHAR2(50) NULL,
    CIUDAD           VARCHAR2(25) NOT NULL,
    DIRECCION        VARCHAR2(50) NOT NULL,
    TELEFONO         VARCHAR2(9)  NULL,
    FECHA_NACIMIENTO DATE         NOT NULL,
    SEXO             CHAR(1)      NOT NULL,
    TIPO             VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY (ID),
    CONSTRAINT CKC_SEXO_PERSONA CHECK (SEXO IN ('M','H','I'))
);

ALTER TABLE PERSONA ADD CONSTRAINT CKC_TIPO_PERSONA
CHECK (TIPO IN('PROFESOR','ALUMNO'));

CREATE TABLE DEPARTAMENTO(
    ID               NUMBER(10)   NOT NULL,
    NOMBRE           VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID)
);

CREATE TABLE GRADO(
    ID               NUMBER(10)   NOT NULL,
    NOMBRE           VARCHAR2(100)NOT NULL,
    CONSTRAINT PK_GRADO PRIMARY KEY (ID)
);

CREATE TABLE CURSO_ESCOLAR
(
    ID               NUMBER(10)   NOT NULL,
    ANYO_INICIO      NUMBER(4)    NOT NULL,
    ANYO_FIN         NUMBER(4)    NOT NULL,
    CONSTRAINT PK_CURSO_ESCOLAR PRIMARY KEY (ID)
);

CREATE TABLE PROFESOR(
    ID_PROFESOR      NUMBER(10)   NOT NULL,
    ID_DEPARTAMENTO  NUMBER(10)   NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY (ID_PROFESOR),
    CONSTRAINT FK_PROFESOR_PERSONA
        FOREIGN KEY (ID_PROFESOR) REFERENCES PERSONA(ID),
    CONSTRAINT FK_PROFESOR_DEPARTAMENTO
        FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID)
);

CREATE TABLE ASIGNATURA(
    ID               NUMBER(10)     NOT NULL,
    NOMBRE           VARCHAR2(100)  NOT NULL,
    CREDITOS         NUMBER(3,1)    NOT NULL,
    TIPO             VARCHAR2(10)   NOT NULL,
    CURSO            NUMBER(1)      NOT NULL,
    CUATRIMESTRE     NUMBER(1)      NOT NULL,
    ID_PROFESOR      NUMBER(10)     NULL,
    ID_GRADO         NUMBER(10)     NOT NULL,
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY(ID)
);

INSERT INTO PERSONA (ID, NIF, NOMBRE, APELLIDO1, APELLIDO2, CIUDAD, DIRECCION, TELEFONO, FECHA_NACIMIENTO, SEXO, TIPO)
VALUES (101, '12345678A', 'Ana', 'García', 'López', 'Madrid', 'Calle Mayor 123', '600112233', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'H', 'ALUMNO');

INSERT INTO PERSONA (ID, NIF, NOMBRE, APELLIDO1, APELLIDO2, CIUDAD, DIRECCION, TELEFONO, FECHA_NACIMIENTO, SEXO, TIPO)
VALUES (102, '87654321B', 'Carlos', 'Martínez', NULL, 'Barcelona', 'Avenida Diagonal 45', '611223344', TO_DATE('1985-11-20', 'YYYY-MM-DD'), 'M', 'PROFESOR');

INSERT INTO PERSONA (ID, NIF, NOMBRE, APELLIDO1, APELLIDO2, CIUDAD, DIRECCION, TELEFONO, FECHA_NACIMIENTO, SEXO, TIPO)
VALUES (103, '98765432C', 'Isabel', 'Fernández', 'Ruiz', 'Valencia', 'Plaza del Sol 7', NULL, TO_DATE('1998-03-01', 'YYYY-MM-DD'), 'I', 'ALUMNO');
