CREATE TABLE REGIONS (
    REGION_ID   NUMBER(10)     NOT NULL,
    REGION_NAME VARCHAR2(25)   NOT NULL,
    CONSTRAINT PK_REGIONS PRIMARY KEY (REGION_ID)
);

CREATE TABLE COUNTRIES (
    COUNTRY_ID   CHAR(2)       NOT NULL,
    COUNTRY_NAME VARCHAR2(40)  NOT NULL,
    REGION_ID    NUMBER(10)    NOT NULL,
    CONSTRAINT PK_COUNTRIES PRIMARY KEY (COUNTRY_ID),
    CONSTRAINT FK_COUNTRIES_REGIONS
        FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

CREATE TABLE LOCATIONS (
    LOCATION_ID    NUMBER(10)    NOT NULL,
    STREET_ADDRESS VARCHAR2(40)  NOT NULL,
    POSTAL_CODE    VARCHAR2(12)  NULL,
    CITY           VARCHAR2(30)  NOT NULL,
    STATE_PROVINCE VARCHAR2(25)  NULL,
    COUNTRY_ID     CHAR(2)       NOT NULL,
    CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID),
    CONSTRAINT FK_LOCATIONS_COUNTRIES
        FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID   NUMBER(10)   NOT NULL,
    DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
    MANAGER_ID      NUMBER(10)   NULL,
    LOCATION_ID     NUMBER(10)   NULL,
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE JOBS (
    JOB_ID     NUMBER(10)    NOT NULL,
    JOB_TITLE  VARCHAR2(35)  NOT NULL,
    MIN_SALARY NUMBER(6)     NULL,
    MAX_SALARY NUMBER(6)     NULL,
    CONSTRAINT PK_JOBS PRIMARY KEY (JOB_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID    NUMBER(10)    NOT NULL,
    FIRST_NAME     VARCHAR2(20)  NOT NULL,
    LAST_NAME      VARCHAR2(25)  NOT NULL,
    EMAIL          VARCHAR2(25)  NOT NULL,
    PHONE_NUMBER   VARCHAR2(20)  NULL,
    HIRE_DATE      DATE          NOT NULL,
    JOB_ID         NUMBER(10)    NOT NULL,
    SALARY         NUMBER(8,2)   NOT NULL,
    COMMISSION_PCT NUMBER(2,2)   NULL,
    MANAGER_ID     NUMBER(10)    NULL,
    DEPARTMENT_ID  NUMBER(10)    NULL,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UK_EMP_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_EMPLOYEES_JOBS
        FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT FK_EMPLOYEES_MANAGER
        FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE JOB_HISTORY (
    EMPLOYEE_ID   NUMBER(10) NOT NULL,
    START_DATE    DATE       NOT NULL,
    END_DATE      DATE       NOT NULL,
    JOB_ID        NUMBER(10) NOT NULL,
    DEPARTMENT_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_JOB_HISTORY PRIMARY KEY (EMPLOYEE_ID, START_DATE),
    CONSTRAINT FK_JH_EMPLOYEES
        FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT FK_JH_JOBS
        FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT FK_JH_DEPARTMENTS
        FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT FK_DEPARTMENTS_MANAGER
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_DEPARTMENTS
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
