/*
DDL
CREATE TABLE identificador
(colunnas)
ALTER
DROP
truncate
Replace

--Tablas
--Vistas
--Procedimentos
--Funciones
--Triggers
--TiposDatos y mas
*/
CREATE TABLE PERSONA(
ID INT NOT NULL,
NIF VARCHAR(9) NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO1 VARCHAR(50) NOT NULL,
APELLIDO2 VARCHAR(50) NULL,
CIUDAD VARCHAR(25)NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR (9) NULL,
FECHA_NACIMIENTO DATE NOT NULL,
SEXO CHAR (1) NOT NULL,
TIPO VARCHAR(10) NOT NULL,
CONSTRAINT PK_PERSONA PRIMARY KEY (ID),
CONSTRAINT CKC_SEXO_PERSONA
CHECK (SEXO IN ('M','H','I'))
);

ALTER TABLE PERSONA ADD CONSTRAINT CKC_TIPO_PERSONA
CHECK (TIPO IN('PROFESOR','ALUMNO'));

CREATE TABLE DEPARTAMENTO(
ID INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL
);

--AGREGAR CON ALTER EN ESTE CASO LA LLAVE PRIMARIA
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPARTAMENTO
PRIMARY KEY (ID);

CREATE TABLE GRADO(
ID INT NOT NULL,
NOMBRE VARCHAR(100)NOT NULL,
CONSTRAINT PK_GRADO
PRIMARY KEY (ID)
);

CREATE TABLE CURSO_ESCOLAR
(
ID INT NOT NULL,
ANYO_INICIO INT NOT NULL,
ANYO_FIN INT NOT NULL,
CONSTRAINT PK_CURSO_ESCOLAR
PRIMARY KEY (ID)
);

--A PARTIR DE ESTAS TABAS SE EMPIESAN A METER LLAVES FORANIAS
CREATE TABLE PROFESOR(
ID_PROFESOR INT NOT NULL,
ID_DEPARTAMENTO INT NOT NULL,
CONSTRAINT PK_PROFESOR
PRIMARY KEY (ID_PROFESOR),
--PARTE NUEVA LLAVES FORANEAS
/*PREFIJO NOMENCLATURA FK_TABLAACTUAL_TABLARELACION*/
CONSTRAINT FK_PROFESOR_PERSONA
FOREIGN KEY (ID_PROFESOR) REFERENCES PERSONA(ID),
CONSTRAINT FK_PROFESOR_DEPARTAMENTO
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID)
);

CREATE TABLE ASIGNATURA(
ID INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
CREDITOS FLOAT NOT NULL,
TIPO VARCHAR(10) NOT NULL,
CURSO INT NOT NULL,
CUATRIMESTRE INT NOT NULL,
ID_PROFESOR INT NULL,
ID_GRADO INT NOT NULL,
CONSTRAINT PK_ASIGNATURA
PRIMARY KEY(ID)
);

/*ALTER TABLE ASIGNATURA
ADD CONSTRAINT FK_ASIGNATURA_PROFESOR
FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR
ADD CONSTRAINT FK_ASIGNATURA_GRADO
FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID);*/


ALTER TABLE ASIGNATURA
ADD CONSTRAINT FK_ASIGNATURA_PROFESOR
FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR); 

ALTER TABLE ASIGNATURA
ADD CONSTRAINT FK_ASIGNATURA_GRADO
FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID); 

DROP TABLE ASIGNATURA;-- tenia error en grado y la tuvevque hacerlo d n

CREATE TABLE ALUMNO_X_ASIGNATURA
(
ID_ALUMNO INT NOT NULL,
ID_ASIGNATURA INT NOT NULL,
ID_CURSO_ESCOLAR INT NOT NULL,
CONSTRAINT PK_ALUMNO_X_ASIGNATURA
PRIMARY KEY(ID_ALUMNO, ID_ASIGNATURA, ID_CURSO_ESCOLAR),
CONSTRAINT FK_ALUMNO_X_ASIGNATURA_PERSONA
FOREIGN KEY (ID_ALUMNO) REFERENCES PERSONA(ID),
CONSTRAINT FK_ALUMNO_X_ASIGNATURA_ASIGNATURA
FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA(ID),
CONSTRAINT FK_ALUMNO_X_ASIGNATURA_CURSO_ESCOLAR
FOREIGN KEY (ID_CURSO_ESCOLAR) REFERENCES CURSO_ESCOLAR (ID)
);


